[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

remappings = [
    "@chainlink/contracts/=chainlink-brownie-contracts/contracts/src/v0.8/"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
base_sepolia = { key = "${ETHERSCAN_API_KEY}" }
